# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the arXiv preprint from the npj manuscript.

Third venue, same science.  The npj file stays the single source of truth, as it
already is for the Corrosion Science version, so a correction to the science is
made in one place and propagates to all three.  What changes here is the class
(article + arxiv.sty instead of sn-jnl), the front matter (sn-jnl's \\fnm/\\sur/
\\affil markup has no equivalent outside the template), and the back matter
(\\bmhead becomes an ordinary starred section).  Section order is left exactly as
the npj file has it, because the preprint should read as the submitted paper.

arxiv.sty comes from paper/arxiv.zip, the template used for previous preprints
from this group.  The zip itself is a local input and is not committed: it is
3 MB, almost all of it another paper's PDF, and only the 7 kB style file is
wanted.  That file is vendored into paper/arxiv/, and refreshed from the zip
whenever the zip is present.

Writes paper/arxiv/ as a self-contained submission directory: main.tex,
supplementary.tex, references.bib, arxiv.sty and figures/.

Run:  python scripts/make_arxiv_version.py
"""

from __future__ import annotations

import re
import shutil
import zipfile

from htw_pdm.paths import PAPER as P
from htw_pdm.paths import ROOT

SRC = (P / "main-snjnl.tex").read_text(encoding="utf-8")
DEST = P / "arxiv"
DEST.mkdir(exist_ok=True)


def braced(cmd: str, s: str) -> str:
    """The brace-balanced argument of \\cmd{...} (skipping any [..] option)."""
    i = s.index(f"\\{cmd}")
    i += len(cmd) + 1
    if s[i] == "[":
        i = s.index("]", i) + 1
    assert s[i] == "{", cmd
    d, start = 1, i + 1
    for j in range(start, len(s)):
        if s[j] == "{":
            d += 1
        elif s[j] == "}":
            d -= 1
            if d == 0:
                return s[start:j]
    raise ValueError(cmd)


title = " ".join(braced("title", SRC).split())
abstract = braced("abstract", SRC).strip()
keywords = " ".join(braced("keywords", SRC).split())

body = SRC[SRC.index("\\section{Introduction}"):SRC.index("\\backmatter")].rstrip()

back = SRC[SRC.index("\\backmatter"):SRC.index("\\bibliography{")]
back = back.replace("\\backmatter", "").strip()
back = re.sub(r"\\bmhead\{([^}]*)\}", r"\\section*{\1}", back)

PREAMBLE = rf"""%% main.tex -- arXiv preprint version.
%% GENERATED by scripts/make_arxiv_version.py from paper/main-snjnl.tex.
%% Do not edit here; edit the npj manuscript and re-run the generator.

\documentclass[10pt,a4paper]{{article}}

\usepackage{{arxiv}}
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage{{amsmath,amssymb,amsfonts}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage{{xcolor}}
\usepackage{{url}}
\usepackage{{float}}
\usepackage{{placeins}}
\usepackage[numbers,sort&compress]{{natbib}}
\usepackage{{hyperref}}

\graphicspath{{{{figures/}}}}

\title{{{title}}}

\author{{%
  Conrard Giresse Tetsassi Feugmo\\[2pt]
  \small Department of Chemistry and Department of Physics \& Astronomy,\\
  \small University of Waterloo, 200 University Avenue West,\\
  \small Waterloo, Ontario N2L 3G1, Canada\\[2pt]
  \small \href{{mailto:cgtetsas@uwaterloo.ca}}{{cgtetsas@uwaterloo.ca}}\\
  \small ORCID 0000-0002-8992-4335
}}

\date{{}}

\begin{{document}}
\maketitle

\begin{{abstract}}
{abstract}
\end{{abstract}}

\noindent\textbf{{Keywords:}} {keywords}

"""

TAIL = r"""
\bibliographystyle{unsrtnat}
\bibliography{references}

\end{document}
"""

(DEST / "main.tex").write_text(PREAMBLE + body + "\n\n" + back + "\n" + TAIL,
                               encoding="utf-8")

# arxiv.sty is the one thing this version needs that the repository does not
# already carry; take it from the template zip rather than committing a copy
# whose origin nobody could later reconstruct.
sty = DEST / "arxiv.sty"
if (P / "arxiv.zip").exists():
    with zipfile.ZipFile(P / "arxiv.zip") as z:
        name = next(n for n in z.namelist()
                    if n.endswith("arxiv.sty") and not n.startswith("__MACOSX"))
        sty.write_bytes(z.read(name))
elif not sty.exists():
    raise SystemExit(
        "paper/arxiv.zip is absent and paper/arxiv/arxiv.sty has not been "
        "vendored, so there is no style file to build against."
    )

# The supplement is venue-independent, so it is copied verbatim.
for f in ("references.bib", "supplementary.tex", "supplementary-body.tex"):
    shutil.copy2(P / f, DEST / f)

figdst = DEST / "figures"
figdst.mkdir(exist_ok=True)
n = 0
for f in sorted((P / "figures").iterdir()):
    if f.suffix.lower() in (".png", ".pdf"):
        shutil.copy2(f, figdst / f.name)
        n += 1

print(f"wrote {DEST / 'main.tex'} "
      f"({(DEST / 'main.tex').read_text().count(chr(10))} lines)")
print(f"copied: arxiv.sty, references.bib, supplementary, {n} figures")
print(f"relative to {ROOT}")
