"""Regenerate docs/REPRODUCE.md: which command produces which artefact.

The table is derived by scanning each module and script for the output
filenames it writes, so it cannot drift from the code the way a hand-kept
list does.  Run:  python scripts/make_reproduce_doc.py
"""
import pathlib, re
from htw_pdm.paths import ROOT

OUT = ROOT / "outputs"
srcs = sorted(pathlib.Path(ROOT/"src/htw_pdm").glob("*.py")) + \
       sorted(pathlib.Path(ROOT/"scripts").glob("*.py"))
# This script names every artefact in its own FIG table, so it would match
# all of them; exclude it from the scan.
srcs = [s for s in srcs if s.name != "make_reproduce_doc.py"]

def cmd_for(p):
    return (f"python -m htw_pdm.{p.stem}" if p.parent.name == "htw_pdm"
            else f"python scripts/{p.name}")

arts = sorted(p.relative_to(OUT).as_posix() for p in OUT.rglob("*") if p.is_file())
owner = {}
for s in srcs:
    t = s.read_text()
    for a in arts:
        if a.split("/")[-1] in t:
            owner.setdefault(a, set()).add(cmd_for(s))

# A file named by several scripts is produced by the one that is not merely
# reading it; prefer the writer, resolved by hand for the handful of cases.
PRIMARY = {
    "ensemble_members_1000.csv": "python -m htw_pdm.uncertainty_ensemble 1000",
    "paper/fig6_band.npz": "python scripts/plot_results.py",
    "paper/referee_stats.json": "python scripts/make_paper_stats.py",
    "paper/table1_parameters.csv": "python scripts/make_paper_tables.py",
    "plot_fits_vs_data.png": "python scripts/plot_results.py",
    "plot_long_time.png": "python scripts/plot_results.py",
    "plot_profile_likelihood.png": "python scripts/plot_results.py",
    "plot_sensitivity_maps.png": "python scripts/plot_sensitivity_maps.py",
    "plot_uncertainty_ensemble.png": "python -m htw_pdm.uncertainty_ensemble",
    "plot_tier2_composition.png": "python -m htw_pdm.tier2_composition",
    "tier2_identifiability.csv": "python -m htw_pdm.tier2_identifiability",
    "tier2_inverse_fit.csv": "python -m htw_pdm.tier2_inverse",
    "tier2_inverse_fit.json": "python -m htw_pdm.tier2_inverse",
    "tier3_identifiability.csv": "python -m htw_pdm.tier3_identifiability",
    "tier3_identifiability_verdict.json": "python -m htw_pdm.tier3_identifiability",
    "ensemble_summary.csv": "python -m htw_pdm.uncertainty_ensemble",
}
for a in list(owner):
    for k, v in PRIMARY.items():
        if a.endswith(k):
            owner[a] = {v}

FIG = {  # manuscript float -> artefact
    "Fig. 1":  "paper/fig1_model_schematic.png",
    "Fig. 2":  "paper/fig2_baseline_verification.png",
    "Fig. 3":  "paper/fig3_fits_vs_data.png",
    "Fig. 4":  "paper/fig4_profile_likelihood.png",
    "Fig. 5":  "paper/fig5_uncertainty_ensemble.png",
    "Fig. 6":  "paper/fig6_long_time.png",
    "Fig. 7":  "paper/fig7_sensitivity_maps.png",
    "Fig. 8":  "paper/fig8_steady_spatial.png",
    "Fig. 9":  "paper/fig9_transient_qs.png",
    "Fig. 10": "paper/fig10_composition_edx.png",
    "Fig. S-workflow": "paper/fig_nsem_workflow.png",
    "Table 1":  "paper/table1_parameters.csv",
    "Table 2":  "paper/table2_model_ladder.csv",
    "Table 3":  "paper/table3_nsem_accuracy.csv",
    "Table 4":  "paper/table4_f1_exhibit.csv",
    "Table 5":  "paper/table5_t2a_identifiability.csv",
    "Table 6":  "paper/table6_t2e_ni_exhibit.csv",
    "Table 7":  "paper/table7_t3_closure_nogo.csv",
    "Table 8":  "paper/table8_envelope_factors.csv",
    "Table 10": "paper/table10_pbr_closure.csv",
}

L = []
L.append("# Reproducing every number in the paper\n")
L.append("Each manuscript float and every committed artefact, with the exact command\n"
         "that writes it. **This file is generated** by `scripts/make_reproduce_doc.py`,\n"
         "which scans the source for output filenames, so it cannot drift from the code.\n")
L.append("Everything lands under `outputs/`, resolved by `htw_pdm.paths` from the\n"
         "`pyproject.toml` marker — never relative to the working directory. Set\n"
         "`HTW_PDM_ROOT` to redirect it.\n")
L.append("## Ordering\n")
L.append("""Three dependencies are real; the rest is free order.

1. `make_referee_analyses.py` must follow `make_paper_stats.py`, whose 1000-member
   ensemble it propagates.
2. `tier3_forward_envelope` must follow `tier2_inverse`, whose fit it reads from
   `outputs/tier2_inverse_fit.json`.
3. `make_paper_figs.py` must follow `plot_results.py` and `plot_sensitivity_maps.py`,
   whose PNGs it copies into `outputs/paper/`. It now fails loudly if they are absent;
   it used to skip silently, leaving figures 3, 4, 6 and 7 stale.
""")
L.append("## Manuscript floats\n")
L.append("| Float | Artefact | Command |")
L.append("|---|---|---|")
for k, a in FIG.items():
    cmds = sorted(owner.get(a, {"— not regenerated by a tracked script —"}))
    L.append(f"| {k} | `outputs/{a}` | {'<br>'.join('`%s`' % c for c in cmds)} |")

L.append("\n## Every other tracked artefact\n")
L.append("| Artefact | Command |")
L.append("|---|---|")
for a in arts:
    if a in FIG.values():
        continue
    cmds = sorted(owner.get(a, []))
    if not cmds:
        continue
    L.append(f"| `outputs/{a}` | {'<br>'.join('`%s`' % c for c in cmds)} |")

unowned = [a for a in arts if a not in owner and a not in FIG.values()]
L.append("\n## Written under a run directory, not by name\n")
L.append("Hydra run directories and network checkpoints: the trainers name these at\n"
         "run time, so they are listed by the command that produces the directory.\n")
L.append("| Path | Command |")
L.append("|---|---|")
seen = set()
for a in unowned:
    top = a.split("/")[0]
    if top in seen:
        continue
    seen.add(top)
    c = ("`python -m htw_pdm.trainer`" if top.startswith("forward")
         else "`python -m htw_pdm.inverse_trainer`" if top.startswith(("inverse", "nsem", "20"))
         else "`python -m htw_pdm.tier2_identifiability`" if top == "tier2"
         else "—")
    L.append(f"| `outputs/{top}/` | {c} |")

(ROOT/"docs"/"REPRODUCE.md").write_text("\n".join(L) + "\n")
print("wrote docs/REPRODUCE.md")
